### ISSUE TITLE
Application closes shortly after opening

### ISSUE THREAD

**Issue by eric963** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#5]
**Describe the bug**
Added in a couple mods and restarted FASTER with no issues.  Added the rest of the mods about 60 and then when starting FASTER the application closes after a few seconds.  When there are no steam mods added FASTER starts properly with no issues.  Issue appears to happen only after mods are added.  

Windows 10 ver 1903
FASTER x64 version 1.1f

I'm attaching my user.config file

Also here is the error that's generated in the windows event viewer

Application: FASTER.exe
```
CoreCLR Version: 4.700.19.30373
.NET Core Version: 3.0.0-preview6-27804-01
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MaterialDesignThemes.Wpf.DialogHost.set_IsOpen(Boolean value)
   at FASTER.Models.SteamWebApi.ApiCall(String uri) in d:\a\1\s\FASTER\Models\SteamWebApi.cs:line 62
   at FASTER.Models.SteamWebApi.GetSingleFileDetails(Int32 modId) in d:\a\1\s\FASTER\Models\SteamWebApi.cs:line 33
   at FASTER.Models.SteamMod.GetModInfo(Int32 modId) in d:\a\1\s\FASTER\Models\SteamMod.cs:line 195
   at FASTER.Models.SteamMod.UpdateInfoFromSteam() in d:\a\1\s\FASTER\Models\SteamMod.cs:line 216
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at FASTER.SteamMods.SteamMods_Initialized(Object sender, EventArgs e) in d:\a\1\s\FASTER\SteamMods.xaml.cs:line 49
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at FASTER.App.Main()
```

and 

```
Faulting application name: FASTER.exe, version: 1.1.5.0, time stamp: 0x5cf6825d
Faulting module name: KERNELBASE.dll, version: 10.0.18362.239, time stamp: 0xb6f4b059
Exception code: 0xe0434352
Fault offset: 0x000000000003a839
Faulting process id: 0x80
Faulting application start time: 0x01d541b27fa7c484
Faulting application path: G:\Games\Faster\FASTER.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9e102553-96ee-40b2-9788-f6390ae35fe8
Faulting package full name: 
Faulting package-relative application ID: 
```

Have used FAST and FAST2 since it was released and I'm really gald that you have continued on with it.  If there is anything you need me to test or if you need any more info just let me know.

Thanks
Eric Cabral

[user.config.txt](https://github.com/Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite/files/3424489/user.config.txt)

**Comment by Foxlider** [comment]
Wow this is indeed a bad thing. I will be on that ASAP

**Comment by Foxlider** [comment]
Cause found : 
If steam connexion fails, the error message causes an unhandled crash in the application and shuts down.

Workaround : 
No workaround possible. Ensure internet connexion is up and that you can contact steam API : https://steamstat.us/
